apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dedicated-container-ingress-controller

bases:
  - ../manifests

resources:
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
