apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - crd/ingress.kaidotdev.github.io_dedicatedcontaineringresses.yaml
  # +kubebuilder:scaffold:crdkustomizeresource
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - horizontal_pod_autoscaler.yaml
  - pod_disruption_budget.yaml
  - role.yaml
  - role_binding.yaml
  - service.yaml
  - service_account.yaml
