apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dedicated-container-ingress-controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: dedicated-container-ingress-controller
