apiVersion: v1
kind: Service
metadata:
  name: dedicated-container-ingress-controller
spec:
  selector:
    app: dedicated-container-ingress-controller
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http-monitor
      port: 9090
      protocol: TCP
      targetPort: 9090
